apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: aws-demo
spec:
  selector:
    matchLabels:
      app: aws-demo
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: aws-demo
    spec:
      containers:
        - name: aws-demo
          image: 7829099824/aws-demo:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
# The port that the container is running on in the cluster

---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: aws-demo-svc
spec:
  selector:
    app: aws-demo
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer  # type of the service.