#spring.datasource.url=jdbc:mysql://localhost:3306/mydb
#spring.datasource.username=root
#spring.datasource.password=yourpassword
#spring.jpa.hibernate.ddl-auto=update

#scheduler:
#  cron: "0 * * * * ?"  # Every minute
#  retry:
#    maxAttempts: 3
#    delay: 5000  # 5 seconds delay between retries

logging:
  level:
    org.springframework: INFO

spring:
  application:
    name: aws-demo
  server:
    port: 8081

  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  servlet:
    context-path: /aws-demo