#spring:
#  application:
#    name: aws-demo
#  datasource:
#    #url: jdbc:mariadb://${host}:${port}/${dbname}?useSSL=false&allowPublicKeyRetrieval=true
#    username: ${username}
#    password: ${password}
#    hikari:
#      initialization-fail-timeout: 0
#
#  jpa:
#    hibernate:
#      ddl-auto:
#      show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        default_schema: ${dbname}
#        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  servlet:
    context-path: /aws-demo

spring:
  server:
    port: 8080
  application:
    name: aws-demo
  datasource:
    url: jdbc:mariadb://localhost:3306/db_name?useSSL=false&allowPublicKeyRetrieval=true
    username: xxxx
    password: xxxx
    hikari:
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto:
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        default_schema: db_name
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true

logging:
  level:
    io:
      jsonwebtoken: DEBUG
    org:
      springframework:
        security: DEBUG
