#spring:
#  application:
#    name: aws-demo
#  datasource:
#    #url: jdbc:mariadb://${host}:${port}/${dbname}?useSSL=false&allowPublicKeyRetrieval=true
#    username: ${username}
#    password: ${password}
#    hikari:
#      initialization-fail-timeout: 0
#
#  jpa:
#    hibernate:
#      ddl-auto:
#      show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MariaDBDialect
#        default_schema: ${dbname}
#        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring:
  server:
    port: 8080
  application:
    name: aws-demo
  datasource:
    url: jdbc:mariadb://localhost:3306/PI4_IT4_COUNTERPARTY_DB?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Winter@@2024
    hikari:
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto:
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        default_schema: PI4_IT4_COUNTERPARTY_DB
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        format_sql: true

logging:
  level:
    io:
      jsonwebtoken: DEBUG
    org:
      springframework:
        security: DEBUG