apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-demo
  labels:
    app: aws-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aws-demo
  template:
    metadata:
      labels:
        app: aws-demo
    spec:
      containers:
        - name: aws-demo
          image: 7829099824/aws-repo:latest
          ports:
            - containerPort: 8080